export default function StaticPage({ page }) {
  const content = {
    privacy: {
      title: "Privacy Policy",
      body: `Last updated: [DATE]

FREE STATE ACTION NOW — PRIVACY POLICY

1. WHO WE ARE
Free State Action Now ("we", "us", "our") is operated by [REGISTERED ENTITY NAME], registered at [ADDRESS]. Our Information Officer can be contacted at [INFORMATION OFFICER EMAIL].

2. WHAT WE COLLECT
• Account information: email address and display name when you register
• Report content: the text, photos, video, and metadata you submit in a report
• Evidence metadata: GPS coordinates, EXIF capture date, device make/model extracted from uploaded photos
• Votes and comments tied to your account
• Submission IP address and browser fingerprint (for spam and abuse prevention only)
• Standard server logs (IP address, browser type, pages visited)

3. WHY WE COLLECT IT (LAWFUL BASIS — POPIA s11)
• To publish community reports and build a public accountability record (legitimate interest)
• To verify the integrity of evidence (legitimate interest)
• To comply with legal obligations if required (legal obligation)
• Where you have given explicit consent (consent)

4. WHO WE SHARE IT WITH
• Curators and administrators of this platform (internal)
• Admitted attorneys engaged to review legal notices (subject to confidentiality)
• No third-party advertisers. Ever.
• Law enforcement or courts, only on valid legal process

5. RETENTION
Report content is retained indefinitely as part of the public accountability record. You may request deletion of your personal account data. Note: anonymised report content may remain in the public record after account deletion.

6. YOUR RIGHTS (POPIA s23–25)
You have the right to: access your personal information; request correction; request deletion (subject to public interest exceptions); object to processing. Submit requests to [INFORMATION OFFICER EMAIL].

7. COOKIES
See our Cookie Policy for details. We use only essential session cookies and no third-party tracking cookies.

8. SECURITY
Evidence files are stored on encrypted cloud infrastructure. SHA-256 hashes are computed server-side. Passwords are hashed. We conduct annual security reviews.

9. CHILDREN
This platform is not intended for persons under 18. Submitters must confirm they are 18 or older.

10. CHANGES
We will notify registered users of material changes to this policy by email.`,
    },
    terms: {
      title: "Terms of Use",
      body: `Last updated: [DATE]

FREE STATE ACTION NOW — TERMS OF USE

1. ACCEPTANCE
By accessing or using Free State Action Now ("the Platform"), you agree to these Terms. If you do not agree, do not use the Platform.

2. WHO MAY USE THE PLATFORM
You must be 18 or older to submit reports. You may browse the Platform without registering.

3. WHAT THE PLATFORM IS
Free State Action Now is an independent civic-evidence platform. It is not a government service, not a formal complaints process, and not a legal service. Publishing a report here does not by itself create any legal obligation on any municipality.

4. YOUR CONTENT
By submitting a report, you warrant that:
(a) You are the author or have authority to submit it
(b) It is true and accurate to the best of your knowledge
(c) It does not contain defamatory, false, or misleading statements
(d) It does not disclose private personal information of others without consent
(e) It does not violate any applicable law

You grant Free State Action Now a perpetual, royalty-free licence to publish, reproduce, and distribute your submitted content for the Platform's accountability purposes.

5. PROHIBITED CONDUCT
You may not:
• Submit false or fabricated reports
• Impersonate any person or organisation
• Use the Platform for commercial or political campaign purposes
• Attempt to circumvent moderation
• Harass or threaten any person

6. MODERATION
We reserve the right to reject, remove, or modify any content at our discretion. Rejected submissions will be notified with a reason.

7. LEGAL NOTICES
Legal notices generated by the Platform are drafts only. They are not sent without attorney review and approval. Free State Action Now is not your attorney and nothing on this Platform constitutes legal advice.

8. LIMITATION OF LIABILITY
To the fullest extent permitted by law, Free State Action Now is not liable for any loss arising from reliance on Platform content, inaccuracies in directory information, or the outcome of any legal process initiated using Platform evidence.

9. GOVERNING LAW
These Terms are governed by the laws of the Republic of South Africa. Disputes are subject to the jurisdiction of the South African courts.`,
    },
    "acceptable-use": {
      title: "Acceptable Use Policy",
      body: `Last updated: [DATE]

FREE STATE ACTION NOW — ACCEPTABLE USE POLICY

This policy sets out what you may and may not submit to Free State Action Now.

PERMITTED CONTENT
✓ Firsthand accounts of infrastructure failures (roads, water, electricity, sanitation, waste)
✓ Photos and videos taken by you showing the failure
✓ Your personal experience of a public-health or safety risk caused by service failure
✓ Comments providing additional factual context

NOT PERMITTED
✗ Personal disputes between neighbours or private individuals
✗ Commercial or contractual disputes with businesses
✗ Political campaign content or party propaganda
✗ Content that identifies private individuals without their consent
✗ Content that is defamatory, racist, sexist, or hateful
✗ Duplicate reports of the same incident already on file
✗ Fabricated or staged evidence
✗ Content that includes personal financial account numbers, ID numbers, or similar sensitive data

EVIDENCE GUIDELINES
• GPS-tagged photos taken on the day of the incident are strongest
• Include landmarks or street signs where possible
• Do not edit or filter photos submitted as evidence
• Video must be unedited and clearly show the issue described

ENFORCEMENT
Violations of this policy will result in rejection of the submission. Repeated violations may result in account suspension. Fraudulent submissions may be referred to law enforcement.`,
    },
    cookies: {
      title: "Cookie Policy",
      body: `Last updated: [DATE]

FREE STATE ACTION NOW — COOKIE POLICY

We use only the following cookies:

ESSENTIAL COOKIES (cannot be disabled)
• Session cookie: maintains your login session. Expires when you close your browser.
• CSRF token: protects form submissions from cross-site request forgery. Session-based.

WE DO NOT USE:
✗ Advertising cookies
✗ Third-party tracking cookies
✗ Analytics cookies (Google Analytics or similar)
✗ Social media tracking pixels

No cookie consent banner is required because we only use strictly necessary cookies (POPIA and EU GDPR exemption for essential cookies).

If you have questions about our cookie use, contact [INFORMATION OFFICER EMAIL].`,
    },
  };

  const c = content[page];
  if (!c) return <div style={{ color: "#444", padding: "60px", textAlign: "center" }}>Page not found.</div>;

  return (
    <div style={{ maxWidth: "760px", margin: "0 auto", padding: "40px 24px" }}>
      <h1 style={{ color: "#F5F5F0", fontSize: "28px", fontWeight: 800, marginBottom: "32px" }}>{c.title}</h1>
      <div style={{ color: "#888", fontSize: "14px", lineHeight: 2, whiteSpace: "pre-wrap", background: "#111", border: "1px solid #1a1a1a", borderRadius: "8px", padding: "32px" }}>
        {c.body}
      </div>
    </div>
  );
}
